
const addTwoNumbers = (x, y) => {
    return x+y
}

console.log(addTwoNumbers(5, 10))
console.log("I caused a merge conflict.")
